version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: huydz2k1
      POSTGRES_PASSWORD: huydz2k1
      POSTGRES_DB: crawl_data
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # iam-service:
  #   build: ./iam_service
  #   container_name: iam_service
  #   restart: always
  #   environment:
  #     - DATABASE_URL=postgresql://huydz2k1:huydz2k1@db:5432/crawl_data
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=admin
  #     - RABBITMQ_PASSWORD=admin123
  #     - RABBITMQ_VHOST=/
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   ports:
  #     - "5000:5000"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    depends_on:
      - zookeeper

  producer:
    container_name: producer
    build: ./producer
    environment:
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
    depends_on:
      kafka:
        condition: service_healthy

  consumer:
    container_name: consumer
    build: ./consumer
    environment:
      - DATABASE_URL=postgresql://huydz2k1:huydz2k1@db:5432/data
      - KAFKA_BROKER_HOST=kafka
      - KAFKA_BROKER_PORT=9092
    depends_on:
      kafka:
        condition: service_healthy

  kafka-streams:
    container_name: kafka-streams
    build: ./stream_app
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
